# Generated by Django 4.0.1 on 2022-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Team_Information',
        ),
    ]
